<template>
  <div class="edit-page">
    <!-- Page Header -->
    <div class="page-header">
      <h1 class="page-title">Edit Profile</h1>
      <p class="page-subtitle">Update your personal information and avatar</p>
    </div>

    <div class="edit-form-container">
      <el-form
          ref="formRef"
          :model="formData"
          :rules="formRules"
          label-width="120px"
          class="edit-form"
      >
        <!-- Basic Information -->
        <el-form-item label="User ID" prop="id">
          <el-input v-model="formData.id" disabled placeholder="Auto-generated by system"/>
        </el-form-item>

        <el-form-item label="Email" prop="email">
          <el-input v-model="formData.email" disabled placeholder="Email cannot be modified"/>
        </el-form-item>

        <el-form-item label="Nickname" prop="nickname">
          <el-input
              v-model="formData.nickname"
              placeholder="Please enter your nickname"
              maxlength="20"
              show-word-limit
          />
        </el-form-item>

        <el-form-item label="Birth Date" prop="birthdaytime">
          <el-date-picker
              v-model="formData.birthdaytime"
              type="datetime"
              placeholder="Select date and time"
              value-format="YYYY-MM-DD HH:mm:ss"
              format="YYYY-MM-DD HH:mm:ss"
              style="width: 100%"
          />
        </el-form-item>

        <el-form-item label="Avatar" prop="avatar">
          <div class="avatar-section">
            <el-image
                class="avatar-preview"
                :src="formData.avatar"
                :preview-src-list="formData.avatar ? [formData.avatar] : []"
                fit="cover"
                hide-on-click-modal
            >
              <template #error>
                <div class="avatar-placeholder">
                  <span>No Avatar</span>
                </div>
              </template>
            </el-image>

            <el-upload
                v-model:file-list="fileList"
                class="avatar-upload"
                :auto-upload="false"
                :on-change="handleFileChange"
                :on-preview="handlePreview"
                :on-remove="handleRemove"
                :before-remove="beforeRemove"
                :limit="1"
                :multiple="false"
                :on-exceed="handleExceed"
            >
              <el-button type="primary">Upload Avatar</el-button>
              <template #tip>
                <div class="upload-tip">
                  jpg/png files, size less than 500KB
                </div>
              </template>
            </el-upload>
          </div>
        </el-form-item>

        <!-- Action Buttons -->
        <el-form-item class="form-actions">
          <el-button type="primary" @click="handleSubmit" :loading="loading">
            {{ loading ? 'Saving...' : 'Save' }}
          </el-button>
          <el-button @click="handleCancel">Cancel</el-button>
        </el-form-item>
      </el-form>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useAuthStore } from '@/store/auth'
import { useRouter } from 'vue-router'

const router = useRouter()
const authStore = useAuthStore()
const userId = authStore.userInfo?.userId
const token = authStore.token

// Reactive data
const formRef = ref()
const loading = ref(false)
const selectedFile = ref(null)
const fileList = ref([])

const formData = reactive({
  id: null,
  email: '',
  nickname: '',
  avatar: '',
  birthdaytime: null,
  status: 1
})

const formRules = {
  nickname: [
    { required: true, message: 'Please enter nickname', trigger: 'blur' },
    { min: 2, max: 20, message: 'Nickname length 2-20 characters', trigger: 'blur' }
  ]
}

// File upload handlers
const handleRemove = (file, uploadFiles) => {
  selectedFile.value = null
  fileList.value = []
  console.log(file, uploadFiles)
}

const handleFileChange = (file, fileList) => {
  if (fileList.length > 0) {
    selectedFile.value = file.raw
    formData.avatar = URL.createObjectURL(file.raw)
  } else {
    selectedFile.value = null
  }
}

const handlePreview = (uploadFile) => {
  console.log(uploadFile)
}

const handleExceed = (files, uploadFiles) => {
  ElMessage.warning(
      `Limit is 1 file, you selected ${files.length} files this time, total ${files.length + uploadFiles.length} files`
  )
}

const beforeRemove = (uploadFile, uploadFiles) => {
  return ElMessageBox.confirm(
      `Cancel the transfer of ${uploadFile.name}?`
  ).then(
      () => true,
      () => false
  )
}

// Fetch user data
const fetchDataDetail = async () => {
  try {
    loading.value = true
    const response = await fetch(`/api/users/getuserinfor/${userId}`, {
      headers: {
        'Authorization': token ? `Bearer ${token}` : '',
        'Content-Type': 'application/json'
      }
    })
    if (!response.ok) {
      throw new Error(`HTTP error! Status: ${response.status}`)
    }
    const result = await response.json()
    if (result.code === 200 && result.data) {
      Object.assign(formData, result.data)
    } else {
      throw new Error(result.message || 'Failed to get user information')
    }
  } catch (error) {
    console.error('Failed to get user details:', error)
    ElMessage.error('Failed to get information: ' + error.message)
  } finally {
    loading.value = false
  }
}

// Submit form
const handleSubmit = async () => {
  try {
    await formRef.value.validate()
    loading.value = true

    const formDataToSend = new FormData()
    formDataToSend.append('email', formData.email)
    formDataToSend.append('nickname', formData.nickname)
    formDataToSend.append('avatar', formData.avatar || '')
    formDataToSend.append('status', formData.status.toString())

    if (formData.birthdaytime) {
      const date = new Date(formData.birthdaytime)
      const formattedDateTime = formatToLocalDateTime(date)
      formDataToSend.append('birthdaytime', formattedDateTime)
    } else {
      formDataToSend.append('birthdaytime', '')
    }

    if (selectedFile.value) {
      formDataToSend.append('avatarFile', selectedFile.value)
    }

    const response = await fetch(`/api/users/${userId}/profile`, {
      method: 'PUT',
      headers: {
        'Authorization': token ? `Bearer ${token}` : ''
      },
      body: formDataToSend
    })

    if (!response.ok) {
      throw new Error(`HTTP error! Status: ${response.status}`)
    }

    const result = await response.json()
    if (result.success === true) {
      ElMessage.success('Profile updated successfully')
      router.push('/UserCenter')
    } else {
      throw new Error(result.message || 'Update failed')
    }
  } catch (error) {
    console.error('Failed to update data:', error)
    ElMessage.error('Update failed: ' + error.message)
  } finally {
    loading.value = false
  }
}

// Cancel edit
const handleCancel = () => {
  ElMessageBox.confirm('Are you sure you want to cancel editing? Unsaved changes will be lost.', 'Warning', {
    confirmButtonText: 'Confirm',
    cancelButtonText: 'Cancel',
    type: 'warning'
  }).then(() => {
    router.push('/UserCenter')
  }).catch(() => {
    // User cancelled operation
  })
}

// Helper function to format date
const formatToLocalDateTime = (date) => {
  if (!date) return ''
  const d = new Date(date)
  const year = d.getFullYear()
  const month = String(d.getMonth() + 1).padStart(2, '0')
  const day = String(d.getDate()).padStart(2, '0')
  const hours = String(d.getHours()).padStart(2, '0')
  const minutes = String(d.getMinutes()).padStart(2, '0')
  const seconds = String(d.getSeconds()).padStart(2, '0')
  return `${year}-${month}-${day} ${hours}:${minutes}:${seconds}`
}

// Lifecycle hook
onMounted(() => {
  fetchDataDetail()
})
</script>

<style scoped>
.edit-page {
  min-height: 100vh;
  background-color: #0f172a;
  padding: 30px;
}

.page-header {
  margin-bottom: 30px;
  margin-top: 50px;
  text-align: center;
}

.page-title {
  font-size: 28px;
  font-weight: 600;
  color: #f8fafc;
  margin-bottom: 10px;
}

.page-subtitle {
  color: #94a3b8;
  font-size: 16px;
}

.edit-form-container {
  background: rgba(255, 255, 255, 1);
  border-radius: 12px;
  padding: 30px;
  margin: 0 auto;
  max-width: 600px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.2);
}

.avatar-section {
  display: flex;
  align-items: flex-start;
  gap: 20px;
}

.avatar-preview {
  width: 100px;
  height: 100px;
  border-radius: 8px;
  overflow: hidden;
}

.avatar-placeholder {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background: rgba(15, 23, 42, 0.5);
  color: #94a3b8;
}

.avatar-upload {
  flex: 1;
}

.upload-tip {
  color: #94a3b8;
  font-size: 12px;
  margin-top: 8px;
}

.form-actions {
  margin-top: 30px;
  text-align: center;
}

.form-actions .el-button {
  min-width: 100px;
  margin: 0 10px;
}

/* Deep selectors for Element Plus components */
:deep(.el-form-item__label) {
  color: #e2e8f0 !important;
  font-weight: 500;
}

:deep(.el-input__inner) {
  background-color: rgba(15, 23, 42, 0.5) !important;
  border: 1px solid rgba(148, 163, 184, 0.3) !important;
  color: #e2e8f0 !important;
}

:deep(.el-input__inner:focus) {
  border-color: #3b82f6 !important;
}

:deep(.el-input.is-disabled .el-input__inner) {
  background-color: rgba(15, 23, 42, 0.3) !important;
  color: #94a3b8 !important;
}

:deep(.el-date-editor .el-input__inner) {
  background-color: rgba(15, 23, 42, 0.5) !important;
  color: #e2e8f0 !important;
}

:deep(.el-button) {
  background: rgba(30, 41, 59, 0.8);
  border: 1px solid rgba(148, 163, 184, 0.3);
  color: #e2e8f0;
}

:deep(.el-button:hover) {
  background: rgba(30, 41, 59, 1);
  border-color: #3b82f6;
}

:deep(.el-button--primary) {
  background-color: #3b82f6;
  border-color: #3b82f6;
}

:deep(.el-button--primary:hover) {
  background-color: #2563eb;
  border-color: #2563eb;
}

@media (max-width: 768px) {
  .edit-page {
    padding: 15px;
  }

  .page-header {
    margin-top: 30px;
  }

  .edit-form-container {
    padding: 20px;
  }

  .avatar-section {
    flex-direction: column;
    align-items: center;
  }

  .form-actions .el-button {
    min-width: 80px;
    margin: 5px;
  }
}
</style>