<template>
  <div class="address-dialog">
    <el-form
        ref="formRef"
        :model="formData"
        :rules="formRules"
        label-width="120px"
        class="address-form"
    >
      <!-- Address Basic Information -->
      <el-form-item label="Address ID" prop="id">
        <el-input v-model="formData.id" disabled placeholder="Auto-generated by system"/>
      </el-form-item>

      <el-form-item label="Address Name" prop="addressName">
        <el-input
            v-model="formData.addressName"
            placeholder="Enter address name (e.g. Home, Office)"
            maxlength="50"
            show-word-limit
        />
      </el-form-item>

      <el-form-item label="Default Address" prop="isDefault">
        <el-radio-group v-model="formData.isDefault">
          <el-radio :value="0">Yes</el-radio>
          <el-radio :value="1">No</el-radio>
        </el-radio-group>
      </el-form-item>

      <el-form-item label="Receiver Name" prop="receiverName">
        <el-input
            v-model="formData.receiverName"
            placeholder="Enter receiver name"
            maxlength="100"
            show-word-limit
        />
      </el-form-item>

      <!-- Contact Information -->
      <el-row :gutter="20">
        <el-col :span="12">
          <el-form-item label="Country Code" prop="phoneCountryCode">
            <el-input
                v-model="formData.phoneCountryCode"
                placeholder="e.g. +86"
                maxlength="10"
            />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="Phone Number" prop="phoneNumber">
            <el-input
                v-model="formData.phoneNumber"
                placeholder="Enter phone number"
                maxlength="50"
            />
          </el-form-item>
        </el-col>
      </el-row>

      <el-form-item label="Email Address" prop="email">
        <el-input
            v-model="formData.email"
            placeholder="Enter email address"
            maxlength="100"
        />
      </el-form-item>

      <!-- Address Information -->
      <el-row :gutter="20">
        <el-col :span="12">
          <el-form-item label="Country" prop="country">
            <el-input
                v-model="formData.country"
                placeholder="Enter country"
                maxlength="100"
            />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="State/Province" prop="stateProvince">
            <el-input
                v-model="formData.stateProvince"
                placeholder="Enter state/province"
                maxlength="100"
            />
          </el-form-item>
        </el-col>
      </el-row>

      <el-row :gutter="20">
        <el-col :span="12">
          <el-form-item label="City" prop="city">
            <el-input
                v-model="formData.city"
                placeholder="Enter city"
                maxlength="100"
            />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item label="District" prop="district">
            <el-input
                v-model="formData.district"
                placeholder="Enter district"
                maxlength="100"
            />
          </el-form-item>
        </el-col>
      </el-row>

      <el-form-item label="Street Address" prop="streetAddress">
        <el-input
            v-model="formData.streetAddress"
            type="textarea"
            :rows="3"
            placeholder="Enter detailed address"
            maxlength="500"
            show-word-limit
        />
      </el-form-item>

      <el-form-item label="Postal Code" prop="postalCode">
        <el-input
            v-model="formData.postalCode"
            placeholder="Enter postal code"
            maxlength="20"
        />
      </el-form-item>

      <!-- Action Buttons -->
      <el-form-item class="form-actions">
        <el-button type="primary" @click="handleSubmit" :loading="loading">
          {{ loading ? 'Saving...' : 'Save' }}
        </el-button>
        <el-button @click="handleCancel">Cancel</el-button>
      </el-form-item>
    </el-form>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { useAuthStore } from '@/store/auth'
const authStore = useAuthStore()
const token = authStore.token

// Emits
const emit = defineEmits(['close', 'success'])

// Reactive data
const formRef = ref()
const loading = ref(false)

// Form data
const formData = reactive({
  id: '',
  addressName: '',
  isDefault: 0,
  receiverName: '',
  phoneCountryCode: '+86',
  phoneNumber: '',
  email: '',
  country: 'China',
  stateProvince: '',
  city: '',
  district: '',
  streetAddress: '',
  postalCode: ''
})

// Form validation rules
const formRules = {
  id: [
    { required: true, message: 'Address ID is required', trigger: 'blur' },
    { max: 50, message: 'Address ID cannot exceed 50 characters', trigger: 'blur' }
  ],
  isDefault: [
    { required: true, message: 'Please select default address option', trigger: 'change' }
  ],
  receiverName: [
    { required: true, message: 'Receiver name is required', trigger: 'blur' },
    { max: 100, message: 'Receiver name cannot exceed 100 characters', trigger: 'blur' }
  ],
  phoneCountryCode: [
    { required: true, message: 'Country code is required', trigger: 'blur' },
    { max: 10, message: 'Country code cannot exceed 10 characters', trigger: 'blur' }
  ],
  phoneNumber: [
    { required: true, message: 'Phone number is required', trigger: 'blur' },
    {
      pattern: /^[0-9+\-\s()]{7,20}$/,
      message: 'Invalid phone number format',
      trigger: 'blur'
    },
    { max: 50, message: 'Phone number cannot exceed 50 characters', trigger: 'blur' }
  ],
  email: [
    { type: 'email', message: 'Invalid email format', trigger: 'blur' },
    { max: 100, message: 'Email address cannot exceed 100 characters', trigger: 'blur' }
  ],
  country: [
    { required: true, message: 'Country is required', trigger: 'blur' },
    { max: 100, message: 'Country cannot exceed 100 characters', trigger: 'blur' }
  ],
  stateProvince: [
    { required: true, message: 'State/Province is required', trigger: 'blur' },
    { max: 100, message: 'State/Province cannot exceed 100 characters', trigger: 'blur' }
  ],
  city: [
    { required: true, message: 'City is required', trigger: 'blur' },
    { max: 100, message: 'City cannot exceed 100 characters', trigger: 'blur' }
  ],
  district: [
    { max: 100, message: 'District cannot exceed 100 characters', trigger: 'blur' }
  ],
  streetAddress: [
    { required: true, message: 'Street address is required', trigger: 'blur' },
    { max: 500, message: 'Street address cannot exceed 500 characters', trigger: 'blur' }
  ],
  postalCode: [
    { max: 20, message: 'Postal code cannot exceed 20 characters', trigger: 'blur' }
  ]
}

// Get address details (for editing existing address)
const fetchAddressDetail = async (addressId) => {
  try {
    loading.value = true
    const response = await fetch(`/api/user-address/getById/${addressId}`, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': token ? `Bearer ${token}` : '',
      }
    })
    if (!response.ok) {
      throw new Error(`Request failed, status code: ${response.status}`)
    }
    console.log("Response data:", response)
    const result = await response.json()
    if (result.code === 200) {
      console.log("Result data:", result)
      Object.assign(formData, result.data)
      ElMessage.success('Address data loaded successfully')
    } else {
      throw new Error(result.message || 'Failed to get address information')
    }
  } catch (error) {
    console.error('Failed to get address details:', error)
    ElMessage.error('Failed to get address information: ' + error.message)
    emit('close')
  } finally {
    loading.value = false
  }
}

// Submit form
const handleSubmit = async () => {
  try {
    // Form validation
    await formRef.value.validate()
    loading.value = true

    // Call update API
    const response = await fetch(`/api/user-address/update`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': token ? `Bearer ${token}` : '',
      },
      body: JSON.stringify(formData)
    })
    console.log("Submit data response:", response)
    if (!response.ok) {
      throw new Error(`HTTP error! Status code: ${response.status}`)
    }
    const result = await response.json()
    console.log("Submit data result:", result)
    if (result.code === 200) {
      ElMessage.success('Address updated successfully')
      emit('success')
    } else {
      throw new Error(result.message || 'Update failed')
    }
  } catch (error) {
    console.error('Failed to update address:', error)
    ElMessage.error('Update failed: ' + error.message)
  } finally {
    loading.value = false
  }
}

// Cancel operation
const handleCancel = () => {
  emit('close')
}

// Load data when component mounts (if in edit mode)
onMounted(() => {
  console.log("Received dataId:", props.dataId)
  if (props.dataId) {
    fetchAddressDetail(props.dataId)
  }
})

// Define props
const props = defineProps({
  dataId: {
    type: String,
    default: ''
  }
})

// Watch for addressId changes
watch(() => props.dataId, (newVal) => {
  if (newVal) {
    fetchAddressDetail(newVal)
  }
})
</script>

<style scoped>
.address-dialog {
  min-height: 100vh;
  background-color: #0f172a;
  padding: 30px;
}

.address-form {
  max-width: 800px;
  margin: 0 auto;
  background: rgba(30, 41, 59, 0.6);
  border-radius: 12px;
  padding: 30px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.2);
}

.form-actions {
  margin-top: 30px;
  text-align: center;
}

.form-actions .el-button {
  min-width: 100px;
  margin: 0 10px;
}

/* Form styling for dark theme */
:deep(.el-form-item__label) {
  color: #e2e8f0 !important;
  font-weight: 500;
}

:deep(.el-input__inner) {
  background-color: rgba(15, 23, 42, 0.5) !important;
  border: 1px solid rgba(148, 163, 184, 0.3) !important;
  color: #e2e8f0 !important;
}

:deep(.el-input__inner:focus) {
  border-color: #3b82f6 !important;
}

:deep(.el-textarea__inner) {
  background-color: rgba(15, 23, 42, 0.5) !important;
  border: 1px solid rgba(148, 163, 184, 0.3) !important;
  color: #e2e8f0 !important;
}

:deep(.el-textarea__inner:focus) {
  border-color: #3b82f6 !important;
}

:deep(.el-input.is-disabled .el-input__inner) {
  background-color: rgba(15, 23, 42, 0.3) !important;
  color: #94a3b8 !important;
}

:deep(.el-radio__label) {
  color: #e2e8f0 !important;
}

/* Button styling */
:deep(.el-button) {
  border-radius: 6px;
  transition: all 0.3s ease;
}

:deep(.el-button--primary) {
  background-color: #3b82f6;
  border-color: #3b82f6;
}

:deep(.el-button--primary:hover) {
  background-color: #2563eb;
  border-color: #2563eb;
}

.el-row {
  margin-bottom: 0;
}

.el-col {
  margin-bottom: 0;
}

/* Responsive design */
@media (max-width: 768px) {
  .address-dialog {
    padding: 15px;
  }

  .address-form {
    padding: 20px;
  }

  .form-actions .el-button {
    min-width: 80px;
    margin: 5px;
  }
}
</style>